//RTTI_DECL(Component)
RTTI_DECL(MeshComponent)
RTTI_DECL(AnimPlayComponent)
RTTI_DECL(CollisionComponent)
RTTI_DECL(BoxCollisionComponent)
RTTI_DECL(SphereCollisionComponent)
RTTI_DECL(RigidBodyComponent)
RTTI_DECL(ParticlComponent)
