RTTI_DECL(SceneNode)
RTTI_DECL(GameObject)
RTTI_DECL(Component)
RTTI_DECL(MeshComponent)
RTTI_DECL(SkelMeshComponent)
RTTI_DECL(CollisionComponent)
RTTI_DECL(BoxCollisionComponent)
RTTI_DECL(SphereCollisionComponent)
RTTI_DECL(RigidBodyComponent)

