//RTTI_DECL(PoseModifier)
//RTTI_DECL(LookAtModifier)
RTTI_DECL(Animation)
RTTI_DECL(Skeleton)
RTTI_DECL(AnimationSet)
RTTI_DECL(AnimClipNode)
RTTI_DECL(AnimBlendNode)
RTTI_DECL(AnimLayerNode)
